# Generated by Django 5.1.6 on 2025-02-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enabled',
            field=models.IntegerField(default=1),
        ),
    ]
